// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/zemnmez/tab/types/types.proto

package types

import (
	bytes "bytes"
	encoding_json "encoding/json"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON implements json.Marshaler
func (this ID) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *ID) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this ID) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *ID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this AuthorizationGrant) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *AuthorizationGrant) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this AuthorizationGrant) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *AuthorizationGrant) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this HistoryID) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *HistoryID) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this HistoryID) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *HistoryID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this HistoryItem) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *HistoryItem) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this HistoryItem) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *HistoryItem) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this RegularUserID) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *RegularUserID) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this RegularUserID) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *RegularUserID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this UserID) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *UserID) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this UserID) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *UserID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this RegularUser) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *RegularUser) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this RegularUser) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *RegularUser) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this SpecialUser) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *SpecialUser) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this SpecialUser) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *SpecialUser) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this ItemID) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *ItemID) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this ItemID) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *ItemID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this Item) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *Item) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this Item) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *Item) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this OIDCProviderID) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *OIDCProviderID) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this OIDCProviderID) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *OIDCProviderID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this OIDCProvider) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *OIDCProvider) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this OIDCProvider) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *OIDCProvider) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this IDToken) MarshalJSON() (json []byte, err error) {
	var b bytes.Buffer
	if err = _jsonMarshaler.Marshal(&b, &this); err != nil {
		return
	}
	json = b.Bytes()
	return
}

// UnmarshalJSON implements json.Unmarshaler
func (this *IDToken) UnmarshalJSON(json []byte) (err error) {
	return _jsonUnmarshaler.Unmarshal(bytes.NewReader(json), this)
}

// MarshalGQL implements graphql.Marshaler
func (this IDToken) MarshalGQL(w io.Writer) {
	var err error
	if err = _jsonMarshaler.Marshal(w, &this); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *IDToken) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this Authorization) MarshalJSON() (json []byte, err error) {
	if _, ok := Authorization_name[int32(this)]; !ok {
		return nil, ErrInvalidEnum{EnumName: "Authorization", Value: this}
	}
	return encoding_json.Marshal(this.String())
}

// UnmarshalJSON implements json.Unmarshaler
func (this *Authorization) UnmarshalJSON(json []byte) (err error) {
	var text string
	if err = encoding_json.Unmarshal(json, &text); err != nil {
		return
	}
	var ok bool
	this32 := (*int32)(this)
	if *this32, ok = Authorization_value[text]; !ok {
		return ErrInvalidEnum{EnumName: "Authorization", Value: this}
	}
	return
}

// MarshalGQL implements graphql.Marshaler
func (this Authorization) MarshalGQL(w io.Writer) {
	var err error
	b, err := this.MarshalJSON()
	if err != nil {
		panic(err)
	}
	if _, err = w.Write(b); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *Authorization) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

// MarshalJSON implements json.Marshaler
func (this SpecialUserID) MarshalJSON() (json []byte, err error) {
	if _, ok := SpecialUserID_name[int32(this)]; !ok {
		return nil, ErrInvalidEnum{EnumName: "SpecialUserID", Value: this}
	}
	return encoding_json.Marshal(this.String())
}

// UnmarshalJSON implements json.Unmarshaler
func (this *SpecialUserID) UnmarshalJSON(json []byte) (err error) {
	var text string
	if err = encoding_json.Unmarshal(json, &text); err != nil {
		return
	}
	var ok bool
	this32 := (*int32)(this)
	if *this32, ok = SpecialUserID_value[text]; !ok {
		return ErrInvalidEnum{EnumName: "SpecialUserID", Value: this}
	}
	return
}

// MarshalGQL implements graphql.Marshaler
func (this SpecialUserID) MarshalGQL(w io.Writer) {
	var err error
	b, err := this.MarshalJSON()
	if err != nil {
		panic(err)
	}
	if _, err = w.Write(b); err != nil {
		panic(err)
	}
}

// UnmarshalGQL implements graphql.Unmarshaler
func (this *SpecialUserID) UnmarshalGQL(v interface{}) (err error) {
	var newJSON []byte
	if newJSON, err = encoding_json.Marshal(v); err != nil {
		return
	}
	return this.UnmarshalJSON(newJSON)
}

//these can be set via init() to customise the (un)marshaling
var (
	_jsonMarshaler   github_com_gogo_protobuf_jsonpb.Marshaler
	_jsonUnmarshaler github_com_gogo_protobuf_jsonpb.Unmarshaler
)

type ErrInvalidEnum struct {
	EnumName string
	Value    interface{}
}

func (i ErrInvalidEnum) Error() string { return fmt.Sprintf("invalid %s(%s)", i.EnumName, i.Value) }
