// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolvers

import (
	"time"

	"github.com/zemnmez/tab/types"
)

type AnonymousUser struct {
	ID   types.SpecialUserID `json:"ID"`
	Name string              `json:"Name"`
}

type DefinedItemInput struct {
	Name     string       `json:"Name"`
	Location string       `json:"Location"`
	Parent   *ItemInput   `json:"Parent"`
	Children []*ItemInput `json:"Children"`
}

type IDTokenInput struct {
	Issuer                              string    `json:"Issuer"`
	Subject                             string    `json:"Subject"`
	Audience                            string    `json:"Audience"`
	Expiration                          time.Time `json:"Expiration"`
	Issued                              time.Time `json:"Issued"`
	Nonce                               string    `json:"Nonce"`
	AuthenticationContextClassReference *int      `json:"AuthenticationContextClassReference"`
	AuthenticationMethodsReference      []string  `json:"AuthenticationMethodsReference"`
	AuthorizedParty                     *string   `json:"AuthorizedParty"`
}

type ItemInput struct {
	ByID          *types.ItemID     `json:"ById"`
	WithStructure *DefinedItemInput `json:"WithStructure"`
}

type OIDCProviderInput struct {
	Name string `json:"Name"`
}

type RootUser struct {
	ID   types.SpecialUserID `json:"ID"`
	Name string              `json:"Name"`
}

type Self struct {
	Name           string                      `json:"Name"`
	Authentication *UserAuthentication         `json:"Authentication"`
	Grants         []*types.AuthorizationGrant `json:"Grants"`
	Authorizatons  []types.Authorization       `json:"Authorizatons"`
	// Grant a user some ability the current user has
	Grant User `json:"Grant"`
	// Grant a special user some ability the current user has
	GrantSpecial *types.SpecialUser   `json:"GrantSpecial"`
	History      []*types.HistoryItem `json:"History"`
}

func (Self) IsUser() {}

type UserInput struct {
	Name string `json:"Name"`
}
